//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CprPrototype.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("CprPrototype.Resx.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string CprTabButton {
            get {
                return ResourceManager.GetString("CprTabButton", resourceCulture);
            }
        }
        
        public static string da_CprTabButton {
            get {
                return ResourceManager.GetString("da:CprTabButton", resourceCulture);
            }
        }
        
        public static string HistoryTabButton {
            get {
                return ResourceManager.GetString("HistoryTabButton", resourceCulture);
            }
        }
        
        public static string da_HistoryTabButton {
            get {
                return ResourceManager.GetString("da:HistoryTabButton", resourceCulture);
            }
        }
        
        public static string MedicineTabButton {
            get {
                return ResourceManager.GetString("MedicineTabButton", resourceCulture);
            }
        }
        
        public static string da_MedicineTabButton {
            get {
                return ResourceManager.GetString("da:MedicineTabButton", resourceCulture);
            }
        }
        
        public static string ReasonTabButton {
            get {
                return ResourceManager.GetString("ReasonTabButton", resourceCulture);
            }
        }
        
        public static string da_ReasonTabButton {
            get {
                return ResourceManager.GetString("da:ReasonTabButton", resourceCulture);
            }
        }
        
        public static string ShockableButton {
            get {
                return ResourceManager.GetString("ShockableButton", resourceCulture);
            }
        }
        
        public static string da_ShockableButton {
            get {
                return ResourceManager.GetString("da:ShockableButton", resourceCulture);
            }
        }
        
        public static string NonShockableButton {
            get {
                return ResourceManager.GetString("NonShockableButton", resourceCulture);
            }
        }
        
        public static string da_NonShockableButton {
            get {
                return ResourceManager.GetString("da:NonShockableButton", resourceCulture);
            }
        }
        
        public static string MedicineReminders {
            get {
                return ResourceManager.GetString("MedicineReminders", resourceCulture);
            }
        }
        
        public static string da_MedicineNotification {
            get {
                return ResourceManager.GetString("da:MedicineNotification", resourceCulture);
            }
        }
        
        public static string AssessRhythms {
            get {
                return ResourceManager.GetString("AssessRhythms", resourceCulture);
            }
        }
        
        public static string da_AssessRhythms {
            get {
                return ResourceManager.GetString("da:AssessRhythms", resourceCulture);
            }
        }
        
        public static string CardiopulmonaryResuscitation {
            get {
                return ResourceManager.GetString("CardiopulmonaryResuscitation", resourceCulture);
            }
        }
        
        public static string da_CardiopulmonaryResuscitation {
            get {
                return ResourceManager.GetString("da:CardiopulmonaryResuscitation", resourceCulture);
            }
        }
        
        public static string Cycle {
            get {
                return ResourceManager.GetString("Cycle", resourceCulture);
            }
        }
        
        public static string da_Cycle {
            get {
                return ResourceManager.GetString("da:Cycle", resourceCulture);
            }
        }
        
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        public static string da_History {
            get {
                return ResourceManager.GetString("da:History", resourceCulture);
            }
        }
        
        public static string ShowHistories {
            get {
                return ResourceManager.GetString("ShowHistories", resourceCulture);
            }
        }
        
        public static string da_ShowHistories {
            get {
                return ResourceManager.GetString("da:ShowHistories", resourceCulture);
            }
        }
        
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        public static string da_Actions {
            get {
                return ResourceManager.GetString("da:Actions", resourceCulture);
            }
        }
        
        public static string Give {
            get {
                return ResourceManager.GetString("Give", resourceCulture);
            }
        }
        
        public static string da_Give {
            get {
                return ResourceManager.GetString("da:Give", resourceCulture);
            }
        }
        
        public static string Reasons {
            get {
                return ResourceManager.GetString("Reasons", resourceCulture);
            }
        }
        
        public static string da_Reasons {
            get {
                return ResourceManager.GetString("da:Reasons", resourceCulture);
            }
        }
        
        public static string Hypoxia {
            get {
                return ResourceManager.GetString("Hypoxia", resourceCulture);
            }
        }
        
        public static string da_Hypoxia {
            get {
                return ResourceManager.GetString("da:Hypoxia", resourceCulture);
            }
        }
        
        public static string Hypovolaemia {
            get {
                return ResourceManager.GetString("Hypovolaemia", resourceCulture);
            }
        }
        
        public static string da_Hypovolaemia {
            get {
                return ResourceManager.GetString("da:Hypovolaemia", resourceCulture);
            }
        }
        
        public static string Hyperkalaemia {
            get {
                return ResourceManager.GetString("Hyperkalaemia", resourceCulture);
            }
        }
        
        public static string da_Hyperkalaemia {
            get {
                return ResourceManager.GetString("da:Hyperkalaemia", resourceCulture);
            }
        }
        
        public static string Hypothermia {
            get {
                return ResourceManager.GetString("Hypothermia", resourceCulture);
            }
        }
        
        public static string da_Hypothermia {
            get {
                return ResourceManager.GetString("da:Hypothermia", resourceCulture);
            }
        }
        
        public static string Thrombosis {
            get {
                return ResourceManager.GetString("Thrombosis", resourceCulture);
            }
        }
        
        public static string da_Thrombosis {
            get {
                return ResourceManager.GetString("da:Thrombosis", resourceCulture);
            }
        }
        
        public static string Tension {
            get {
                return ResourceManager.GetString("Tension", resourceCulture);
            }
        }
        
        public static string da_Tension {
            get {
                return ResourceManager.GetString("da:Tension", resourceCulture);
            }
        }
        
        public static string Tamponade {
            get {
                return ResourceManager.GetString("Tamponade", resourceCulture);
            }
        }
        
        public static string da_Tamponade {
            get {
                return ResourceManager.GetString("da:Tamponade", resourceCulture);
            }
        }
        
        public static string Toxins {
            get {
                return ResourceManager.GetString("Toxins", resourceCulture);
            }
        }
        
        public static string da_Toxins {
            get {
                return ResourceManager.GetString("da:Toxins", resourceCulture);
            }
        }
        
        public static string Epinephrine {
            get {
                return ResourceManager.GetString("Epinephrine", resourceCulture);
            }
        }
        
        public static string da_Epinephrine {
            get {
                return ResourceManager.GetString("da:Epinephrine", resourceCulture);
            }
        }
        
        public static string EpinephrineUsage {
            get {
                return ResourceManager.GetString("EpinephrineUsage", resourceCulture);
            }
        }
        
        public static string da_EpinephrineUsage {
            get {
                return ResourceManager.GetString("da:EpinephrineUsage", resourceCulture);
            }
        }
        
        public static string Amiodarone {
            get {
                return ResourceManager.GetString("Amiodarone", resourceCulture);
            }
        }
        
        public static string da_Amiodarone {
            get {
                return ResourceManager.GetString("da:Amiodarone", resourceCulture);
            }
        }
        
        public static string AmiodaroneUsage {
            get {
                return ResourceManager.GetString("AmiodaroneUsage", resourceCulture);
            }
        }
        
        public static string da_AmiodaroneUsage {
            get {
                return ResourceManager.GetString("da:AmiodaroneUsage", resourceCulture);
            }
        }
        
        public static string Bicarbonate {
            get {
                return ResourceManager.GetString("Bicarbonate", resourceCulture);
            }
        }
        
        public static string da_Bicarbonate {
            get {
                return ResourceManager.GetString("da:Bicarbonate", resourceCulture);
            }
        }
        
        public static string BicarbonateUsage {
            get {
                return ResourceManager.GetString("BicarbonateUsage", resourceCulture);
            }
        }
        
        public static string da_BicarbonateUsage {
            get {
                return ResourceManager.GetString("da:BicarbonateUsage", resourceCulture);
            }
        }
        
        public static string Calcium {
            get {
                return ResourceManager.GetString("Calcium", resourceCulture);
            }
        }
        
        public static string da_Calcium {
            get {
                return ResourceManager.GetString("da:Calcium", resourceCulture);
            }
        }
        
        public static string CalciumUsage {
            get {
                return ResourceManager.GetString("CalciumUsage", resourceCulture);
            }
        }
        
        public static string da_CalciumUsage {
            get {
                return ResourceManager.GetString("da:CalciumUsage", resourceCulture);
            }
        }
        
        public static string Magnesium {
            get {
                return ResourceManager.GetString("Magnesium", resourceCulture);
            }
        }
        
        public static string da_Magnesium {
            get {
                return ResourceManager.GetString("da:Magnesium", resourceCulture);
            }
        }
        
        public static string MagnesiumUsage {
            get {
                return ResourceManager.GetString("MagnesiumUsage", resourceCulture);
            }
        }
        
        public static string da_MagnesiumUsage {
            get {
                return ResourceManager.GetString("da:MagnesiumUsage", resourceCulture);
            }
        }
        
        public static string ExtraMedicine {
            get {
                return ResourceManager.GetString("ExtraMedicine", resourceCulture);
            }
        }
        
        public static string da_ExtraMedicine {
            get {
                return ResourceManager.GetString("da:ExtraMedicine", resourceCulture);
            }
        }
        
        public static string given {
            get {
                return ResourceManager.GetString("given", resourceCulture);
            }
        }
        
        public static string da_given {
            get {
                return ResourceManager.GetString("da:given", resourceCulture);
            }
        }
        
        public static string ResuscitationStarted {
            get {
                return ResourceManager.GetString("ResuscitationStarted", resourceCulture);
            }
        }
        
        public static string da_ResuscitationStarted {
            get {
                return ResourceManager.GetString("da:ResuscitationStarted", resourceCulture);
            }
        }
        
        public static string Shockable {
            get {
                return ResourceManager.GetString("Shockable", resourceCulture);
            }
        }
        
        public static string da_Shockable {
            get {
                return ResourceManager.GetString("da:Shockable", resourceCulture);
            }
        }
        
        public static string NonShockable {
            get {
                return ResourceManager.GetString("NonShockable", resourceCulture);
            }
        }
        
        public static string da_NonShockable {
            get {
                return ResourceManager.GetString("da:NonShockable", resourceCulture);
            }
        }
        
        public static string RhythmsAssessed {
            get {
                return ResourceManager.GetString("RhythmsAssessed", resourceCulture);
            }
        }
        
        public static string da_RhythmsAssessed {
            get {
                return ResourceManager.GetString("da:RhythmsAssessed", resourceCulture);
            }
        }
        
        public static string ShockGiven {
            get {
                return ResourceManager.GetString("ShockGiven", resourceCulture);
            }
        }
        
        public static string da_ShockGiven {
            get {
                return ResourceManager.GetString("da:ShockGiven", resourceCulture);
            }
        }
        
        public static string ShockNotGiven {
            get {
                return ResourceManager.GetString("ShockNotGiven", resourceCulture);
            }
        }
        
        public static string da_ShockNotGiven {
            get {
                return ResourceManager.GetString("da:ShockNotGiven", resourceCulture);
            }
        }
        
        public static string CprContinues {
            get {
                return ResourceManager.GetString("CprContinues", resourceCulture);
            }
        }
        
        public static string da_CprContinues {
            get {
                return ResourceManager.GetString("da:CprContinues", resourceCulture);
            }
        }
        
        public static string QuestionShockGiven {
            get {
                return ResourceManager.GetString("QuestionShockGiven", resourceCulture);
            }
        }
        
        public static string da_QuestionShockGiven {
            get {
                return ResourceManager.GetString("da:QuestionShockGiven", resourceCulture);
            }
        }
        
        public static string AnswerShockGiven {
            get {
                return ResourceManager.GetString("AnswerShockGiven", resourceCulture);
            }
        }
        
        public static string da_AnswerShockGiven {
            get {
                return ResourceManager.GetString("da:AnswerShockGiven", resourceCulture);
            }
        }
        
        public static string AnswerShockNotGiven {
            get {
                return ResourceManager.GetString("AnswerShockNotGiven", resourceCulture);
            }
        }
        
        public static string da_AnswerShockNotGiven {
            get {
                return ResourceManager.GetString("da:AnswerShockNotGiven", resourceCulture);
            }
        }
        
        public static string AnswerCancellation {
            get {
                return ResourceManager.GetString("AnswerCancellation", resourceCulture);
            }
        }
        
        public static string da_AnswerCancellation {
            get {
                return ResourceManager.GetString("da:AnswerCancellation", resourceCulture);
            }
        }
        
        public static string QuestionMedicineGiven {
            get {
                return ResourceManager.GetString("QuestionMedicineGiven", resourceCulture);
            }
        }
        
        public static string da_QuestionMedicineGiven {
            get {
                return ResourceManager.GetString("da:QuestionMedicineGiven", resourceCulture);
            }
        }
        
        public static string AnswerConfirm {
            get {
                return ResourceManager.GetString("AnswerConfirm", resourceCulture);
            }
        }
        
        public static string da_AnswerConfirm {
            get {
                return ResourceManager.GetString("da:AnswerConfirm", resourceCulture);
            }
        }
        
        public static string ReminderPrepare {
            get {
                return ResourceManager.GetString("ReminderPrepare", resourceCulture);
            }
        }
        
        public static string da_ReminderPrepare {
            get {
                return ResourceManager.GetString("da:ReminderPrepare", resourceCulture);
            }
        }
        
        public static string ReminderGive {
            get {
                return ResourceManager.GetString("ReminderGive", resourceCulture);
            }
        }
        
        public static string da_ReminderGive {
            get {
                return ResourceManager.GetString("da:ReminderGive", resourceCulture);
            }
        }
        
        public static string Death {
            get {
                return ResourceManager.GetString("Death", resourceCulture);
            }
        }
        
        public static string da_Death {
            get {
                return ResourceManager.GetString("da:Death", resourceCulture);
            }
        }
        
        public static string ROSC {
            get {
                return ResourceManager.GetString("ROSC", resourceCulture);
            }
        }
        
        public static string da_ROSC {
            get {
                return ResourceManager.GetString("da:ROSC", resourceCulture);
            }
        }
        
        public static string HistoryGiven {
            get {
                return ResourceManager.GetString("HistoryGiven", resourceCulture);
            }
        }
        
        public static string da_HistoryGiven {
            get {
                return ResourceManager.GetString("da:HistoryGiven", resourceCulture);
            }
        }
        
        public static string TimingSec {
            get {
                return ResourceManager.GetString("TimingSec", resourceCulture);
            }
        }
        
        public static string da_TimingSec {
            get {
                return ResourceManager.GetString("da:TimingSec", resourceCulture);
            }
        }
        
        public static string TimingMin {
            get {
                return ResourceManager.GetString("TimingMin", resourceCulture);
            }
        }
        
        public static string da_TimingMin {
            get {
                return ResourceManager.GetString("da:TimingMin", resourceCulture);
            }
        }
    }
}
